### ISSUE TITLE
Hino dos rebentos em falta

### ISSUE THREAD

**Issue by 4brunu** [psalterio/repository#18]
Não existe o hino dos rebentos e embora existam muito mais musicas que não estão presentes no psalterio, considero esta muito importante, porque os rebentos já fazem parte do percurso JA oficialmente.
Alem disso, é uma musica que por ser recentes as pessoas têm muita dificuldade com a letra.

**Comment by psalterio** [comment]
Olá Bruno. Se tiveres a letra, os acordes e disponibilidade segue os seguintes passos para adicionar a música:

Mini Tutorial para adicionar musicas no GitHub:
1 - vai à pasta das músicas em português 
https://github.com/psalterio/repository/tree/master/songs/pt
2 - no topo da página onde diz "repository/songs/pt/" carrega no " + " que está ao lado para adicionar um novo ficheiro.
3 - escreve o nome do ficheiro. Neste caso "hino_dos_rebentos.tex".
4 - copia o template. abre uma nova janela no teu browser e copia o conteúdo do template simples que está em https://github.com/psalterio/repository/blob/master/songs/template_simple.tex
6 - decide qual é o id da música. Vai ver a lista de músicas no site http://www.psalterio.net/list-num-desc e usa um numero nas centenas (esquece os números dos milhares, vão desaparecer no futuro). Neste caso usa o numero 198. 
7 - onde diz "Title here" por "Hino dos Rebentos"
8 - id    = {198}
9 - by    = {Autor da musica}, # se nao souberes deixa em branco
10 - depois só falta adicionar a letra e os acordes em cada secção correspondente (\beginverse ...
\endverseç \beginchorus ... \endchorus).  Não faz mal se não tiveres os acordes, podemos sempre adicionar depois. 
11 - carregar no botão “Commit new file”
12 - finalmente para propagar as actualizações do github para a base de dados do psalterio é preciso correr este script http://www.psalterio.net/workshop/tools/db/update_table_songs.php

done!

Se tiveres perguntas diz.

**Comment by 4brunu** [comment]
A musica já foi introduzida pelo @neburpedrosa e tem o ID 221.
@psalterio O Hino dos rebentos devia ter o ID 1 ou pode ficar com o 221?

**Comment by pablomoises** [comment]
@4brunu Uma vez que o ID 1 está vago, faz sentido passa-lo para lá, ficando com a lógica de hinos clubes por faixa etária

**Comment by pablomoises** [comment]
Done ;)
