### ISSUE TITLE
Parser duplica musica quando se muda o ID da mesma

### ISSUE THREAD

**Issue by 4brunu** [psalterio/repository#61]
Se o ID de uma musica for mudado, o parser não vai apagar a antiga, vai apenas adicionar a nova ficando a musica duplicada

**Comment by psalterio** [comment]
ok, obrigado pela lembrança, sim, temos que resolver isto. Podes colocar este issue no bitbucket? este isso é mais técnico e está directamente relacionado com uma função especifica do site. Por aqui podemos usar os "issues" para coisas mais "gerais"?

**Comment by 4brunu** [comment]
Done.
