### ISSUE TITLE
Parser deve criar a ligação na base de dados entre as musicas e a lingua 

### ISSUE THREAD

**Issue by 4brunu** [psalterio/repository#62]
Parser deve criar a ligação na base de dados entre as musicas e a lingua.

Neste momento as musicas não estão associadas às línguas, embora a relação exista na base de dados, não está a ser preenchida.

Isto vai ser necessário para suportar varias linguas.

**Comment by psalterio** [comment]
ok :+1: vamos colocar este issue também no bitbucket

**Comment by 4brunu** [comment]
Done
