### ISSUE TITLE
Musica exemplo aparece nas aplicações

### ISSUE THREAD

**Issue by 4brunu** [psalterio/repository#68]
Na lista de musicas das aplicações moveis, aprece uma musica "Exemplo".
Penso que será esta: https://github.com/psalterio/repository/blob/d18311a9f11d263be664ab69d78b9edee0f7325d/songs/pt/renascer.tex

Pode-se apagar ou ela tem alguma utilidade?

**Comment by psalterio** [comment]
good catch! Essa música tem que ser atualizada. É uma música da Christine Esteves. Vou mudar o titulo para não fazer confusão e depois há-de-se por a letra e os acordes com tempo.

**Comment by tomasm123** [comment]
tambem esta aqui https://github.com/psalterio/repository/blob/d18311a9f11d263be664ab69d78b9edee0f7325d/songs/pt/jerusalem.tex

**Comment by psalterio** [comment]
ok, agora a música com id 116 já não é mais "exemplo", é "renascer". Não sei porque estava tao confuso mas da facto era um "placeholder" para o "renascer". Talvez fosse porque o template antes tinha como exemplo a música "Jerusalém". Obrigados :)
