### ISSUE TITLE
Partituras da Separata do Psaltério #1 até ao #10

### ISSUE THREAD

**Issue by psalterio** [psalterio/repository#73]

**Comment by jcalado** [comment]
Tentei agora converter uma das músicas do sibelius para musicxml e depois para musescore.
Alguém me pode confirmar se é isto que se pretende para o ficheiro final?

Commit:
https://github.com/psalterio/repository/commit/3665c30e7362184c35793ce9d3bd1bb15231f086

**Comment by psalterio** [comment]
Obrigado Joel :+1: 
a conversão para musicxml é apenas um passo intermédio. Depois de converter a música em musescore podes apagar a música em musicxml. Quanto ao ficheiro do musescore converte para mscx (ascii) em vez de mscz (binary) assim é mais fácil de fazer merge de músicas em musescore no github. Depois da conversão feita podes mover o ficheiro original em sibelius para a pasta "done"

**Comment by psalterio** [comment]
músicas do 1 ao 10 que existiam em sibelius já foram convertidas
